frase = '   Curso em video python   '

print(frase[9])
print(frase[9:14])
print(frase[9:14:2])
print(frase[9:])
print(frase[:9])
print(frase[9::3])
print(frase[::3])
print('==================================================================================================')
print(len(frase))
print(frase.count('o'))
print(frase.count('o',0,13))
print(frase.find('deo'))
print(frase.find('Android'))
print('Curso' in frase)
print('==================================================================================================')
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.upper().count('O'))
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print('==================================================================================================')
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print('==================================================================================================')
print(frase.split())
print(frase.replace(" ","*"))
print(frase.replace(" ",""))
print('-'.join(frase))
print('==================================================================================================')
print("""Eu gosto de conversar com você Você é muito simpático e inteligente Você me faz aprender coisas novas Você me diverte com suas perguntas Você é o melhor amigo que um Bing pode ter""")